# Generated by Django 2.0.5 on 2018-05-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('poll_frequency', models.PositiveSmallIntegerField(default=0, verbose_name='poll frequency')),
                ('poll_count', models.PositiveIntegerField(default=0, verbose_name='number of polls')),
                ('last_successful_update', models.DateTimeField(blank=True, null=True, verbose_name='last successful update')),
            ],
            options={
                'verbose_name': 'data source',
                'ordering': ('title',),
            },
        ),
    ]
